# CI de Nível 02 - Disparo agendado

# nome do nosso 'pipeline'
name: 'Execução Agendada'

# Regras de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch (fluxo de trabalho)

on:
  schedule:
    - cron: '0 6 * * 1'

# trabalhos/tarefas dentro do pipeline = jobs

jobs:
  e2e-testes:
    # máquina que o job vai executar
    runs-on: ubuntu-latest

    #passos para rodar os testes (scripts)
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das dependencias
      - name: Instalando dependencias
        run: yarn

      # instalação Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e
#a - minuto
#b - hora
#c - dia do mês
#d - mês
#e - dia da semana

#rodar o regressivo toda segunda-feira pela manhã

# 'expressão cron'
#a b c d e
#0 6 * * 1

