# CI de Nível 04 - Disparo dos testes dentro do pipe de dev

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspecao:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4
    
    - name: Instalando yarn
      run: npm install -g yarn
      
    - name: Intalando Dependências
      run: yarn
      
    - name: Checando padronizacao do código   #Inspeciona/ verifica se o código está padronizado
      run: yarn lint

  unidade:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4
    
    - name: Instalando yarn
      run: npm install -g yarn
      
    - name: Intalando Dependências
      run: yarn
      
    - name: Executando teste de unidade
      run: yarn test

  e2e-tests:
   runs-on: ubuntu-latest

   steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das dependencias
      - name: Instalando dependencias
        run: yarn 

      # instalação Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e  

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report  

  deploy:
   runs-on: ubuntu-latest

   steps:
    - name: Simulação do Deploy
      run: echo "Simulando o Deploy"     
